### PR TITLE
Useful reprs for all objects.

### PR DESCRIPTION
**Pull request by DerrickRice**
# ↪️ Pull Request

Issue #78 

The goal is to show useful values for developers during exploration,
debugging, or logging. These reprs do not show all possible
distinguishing values. The repr format is not documented and may change
without notice.

## 💻 Examples

```text
unify: tamr_unify_client.client.Client(host='localhost', protocol='https', port=4443, base_path='api/versioned/v1/', auth=UsernamePasswordAuth)
project: tamr_unify_client.models.project.mastering.MasteringProject(relative_id='projects/3', name='idogs', type='DEDUP')
```

## ✔️ PR Todo

- [X] Added/updated testing for this change
- [X] Included links to related issues/PRs
- [X] Update relevant [docs](https://github.com/Datatamer/unify-client-python/tree/master/docs) + docstrings
- [X] Update the [CHANGELOG](https://github.com/Datatamer/unify-client-python/blob/master/CHANGELOG.md) under the current `-dev` version:
  - Add changelog entries under any that apply: **ADDED**, **FIXED**, **REMOVED**.
  - Changelog entry format: `[#<issue number>](<link to issue>) <change description>`

### CODE REVIEW

**Comment by DerrickRice** [comment]
Currently, some repr's can raise exceptions. reprs should endeavor to be exception-free.

The cause of the exception is missing `data` values. (See #62 )

Possible paths forward:

- Catch certain exceptions (i.e. KeyError) in `__repr__` methods
- change property getter to use `self.data.get('foo')` which will return `None`, rather than fail-fast on missing values.
- change `__repr__` to use `self.data.get('foo')` rather than `self.foo` property getter.

I suggest either the second or third oprtion. The disadvantage with the first is that it hides all other useful information if just one getter fails.

I propose tacking the relevant change onto this pull request as a separate commit. Waiting for comment from the maintainers.

**Comment by pcattori** [comment]
@DerrickRice , agreed. Let's go with approach 2 (changing property getters to use `.get`)

**Comment by DerrickRice** [comment]
@pcattori - exception-free changes tacked on. As an internal change, I didn't add a changelog entry for that particular commit.

**Comment by pcattori** [comment]
@DerrickRice there's a slight breaking change here in that `KeyError` is no longer thrown by property getters, but rather `None` can be returned instead now. Could you add a message to that effect under **REMOVED** in the changelog?

---

P.S. Realizing that **REMOVED** might not be the best name for the section. Instead, we could say:

1. **BREAKING CHANGES**, **NEW FEATURES**, **BUG FIXES**
2. **CHANGED**, **ADDED**, **FIXED**

I like (1) best.

**Comment by DerrickRice** [comment]
> BREAKING CHANGES, NEW FEATURES, BUG FIXES

Sounds good.

I can imagine some things being debatable between bug fixes and breaking changes ("Is the new behavior the one that was always intended, therefore it's a bug fix? Or is the new behavior one that is a recent decision, therefore it's a breaking change?")

I expect most things to fall into a single category, though.

**Comment by pcattori** [comment]
@DerrickRice just merged #85 so that the new changelog sections naming/ordering is consistent with PR templates. Could you rebase and order the sections as described in #85?

**Comment by DerrickRice** [comment]
I think we're good to go, @pcattori

**Pull request merged**
